Documentation/CONFIGURATION.md, Documentation/CONTRIBUTING.md, Documentation/INSTALLATION.md, Documentation/OPENING-ISSUES.md, Documentation/OTHER-FUNCTIONS.md, Documentation/README.md, Documentation/TROUBLESHOOTING.md, README.md
A reworking of the documentation to break them up into smaller chunks. Hopefully easier to digest that way.
=> 1.0.6 readme update

etc/fastly.vcl
Instead of stripping AE from req, strip it from bereq instead.
This way, the Vary header can be unaltered, and origin will not
receive the AE header.
Minor point, text/html and text/xml should not have been in the
regex for compressing.
=> Do Vary on Accept-Encoding properly

etc/fastly.vcl
This pull contains a fix to Accept-Encoding and changes some of our internal VCL logic to use cookie accessors instead of regexes.
=> VCL fixes and improvements

Model/Layout/LayoutPlugin.php, etc/fastly.vcl
It's intended to help debug issues.
=> Add a header to the Fastly module to indicate that request is passing through it

etc/fastly.vcl
Due to resetting of Cache-Control headers edge nodes will not cache non-static assets. This fixes it.
=> Edge caching broken for non-static assets broken when shielding

Setup/UpgradeData.php, etc/module.xml
If old configuration values exist, they're fetched and saved to new config paths.
=> Added upgrade data script

Observer/InvalidateVarnishObserver.php
Fixed an issue of sending 5 purge request instead of 1 when saving a product.
=> Fixed multiple purge requests issue

Observer/InvalidateVarnishObserver.php
Reverts fastly/fastly-magento2#73
=> Revert "Fixed multiple purge requests issue"

Model/Api.php, Observer/InvalidateVarnishObserver.php
Surrogate keys are sent as POST body in JSON.
=> Implemented surrogate keys batch purge

Controller/Adminhtml/FastlyCdn/Edge/Dictionary/Item/Delete.php, Model/Api.php, view/adminhtml/templates/system/config/dialogs.phtml, view/adminhtml/web/js/uploadvcl.js
=> Improved Edge Dictionary Items

etc/vcl_snippets/fetch.vcl, etc/vcl_snippets/recv.vcl
Various safety, debugging, and performance improvements
=> Vcl tweaks

Observer/SendInstalledRequestToGA.php
Notice: Undefined property: Fastly\Cdn\Observer\SendInstalledRequestToGA::$_helper in /app/vendor/fastly/magento2/Observer/SendInstalledRequestToGA.php on line 112
=> Fix Undefined property error

Model/Config/Backend/PixelRatios.php, etc/adminhtml/system.xml
Replaced checkboxes with a multiselect field
=> Changed device pixel ratios checkboxes to multiselect

Block/GeoIp/GetAction.php, Model/Layout/LayoutPlugin.php, Observer/MarkEsiBlock.php, Observer/MarkEsiPage.php, etc/frontend/events.xml
Apply same tag to esi controller, otherwise compression will kick in
=> Marke the pages with embedded ESI with X-Esi header

Controller/GeoIP/GetAction.php
Resolve the issue where geo ip block was not marked with x-esi header
=> Add x-esi header to geoip block

etc/adminhtml/di.xml
Change Plugin name from: `inchoo` to `fastly`
=> Update name of Plugin

Model/View/Asset/Image.php
specify type in phpdoc resolves error during compilation
=> resolves compilation error caused by 97460af

etc/vcl_snippets/fetch.vcl, etc/vcl_snippets/recv.vcl
=> Graphql vary headers

view/adminhtml/templates/system/config/dialogs.phtml
@vvuksan I simply copied elements from Tango page and merged some additional texts (e.g, "recommended" info)
=> Update shielding POP info

etc/adminhtml/system.xml, view/adminhtml/layout/default.xml, view/adminhtml/web/css/fastly.css
- Revert field type to "text" for `fastly_api_key`
- Add new `masked` css class
- Implement styles to blur content except on hover and focus
=> M095M01A-3 [Magento 2] Hide API token

Controller/Adminhtml/FastlyCdn/CustomSnippet/ChangeUpdateFlag.php, Controller/Adminhtml/FastlyCdn/Vcl/DismissWarning.php, Controller/Adminhtml/FastlyCdn/Vcl/Upload.php
- Manually add default argument values to Config::saveConfig() to support all Magento 2.2.x versions
=> feature/M095M01A-10 [Magento 2] Github issue fastly/fastly-magento2#355

Controller/Adminhtml/FastlyCdn/Backend/DeleteBackend.php, Model/Api.php, view/adminhtml/templates/system/config/dialogs.phtml, view/adminhtml/templates/system/config/form/field/backend.phtml, view/adminhtml/web/js/backends.js
- Add action button to delete backend with dialog confirmation
- Add API endpoint to delete backends
- Implemente request flow with service check, version validation, messages and comment
=> feature/M095M01A-11 [MAGENTO 2] Add ability to remove backends

Model/FrontControllerPlugin.php
- Move variable declaration to proper scope
=> M095M01A-14 Repository error

view/adminhtml/web/js/modly.js
- Added dummy "toggle:true" flag to object to avoid empty object for jquery ajax request when disabling all edge modules
=> feature/M095M01A-21 Issues with Edge Modules

etc/di.xml, etc/frontend/di.xml
- Moved the Image preferences from frontend to global area, to allow use on adminhtml and cron areas too.
=> feature/M095M01A-20 Sitemap generation issue

Documentation/Guides/Edge-Modules/EDGE-MODULE-DATADOME-INTEGRATION.md
Add link to DataDome's website
=> DataDome documentation update

Model/FrontControllerPlugin.php, etc/webapi/di.xml
Add Rate limit for WebApi Calls
=> M095M01A-22 [Magento 2] Add Rate Limit WebApi

etc/fastly_edge_modules/datadome_integration.json
=> Fix label, description and required value

Helper/Data.php, view/adminhtml/templates/system/config/dialogs.phtml
- Adds New Relic Logs to log endpoint options
=> feature/M095M01A-16 [MAGENTO 2] New Relic logging endpoint

Model/FrontControllerPlugin.php
Imagine having thousands of request per minute, and on every request, PHP needs to read a file in filesystem...
PR for this issue: #399
=> Reading content from .maintenance.ip file takes too long

Helper/AutomaticCompression.php, Model/Config.php, Model/Config/Backend/AutomaticCompression.php, Model/Product/Image.php, Model/View/Asset/Image.php, Observer/ConfigurationSave.php, Setup/UpgradeData.php, etc/adminhtml/system.xml, etc/module.xml, etc/vcl_snippets_image_optimizations/recv.vcl
- Added new system.xml config option for Automatic Compression
- Detects when option is changed, and updates VCL Snippet for IO
- Inserts or removes 'optimize' string in VCL depending on value
- Replaces 'quality' query param in Image URL when enabled
- Adds system notification to advise user when modules is updated
=> feature/M095M01A-34 [MAGENTO 2] Image Optimization new optimize option

Controller/Adminhtml/FastlyCdn/Backend/ConfigureBackend.php, Controller/Adminhtml/FastlyCdn/Backend/CreateBackend.php
to prevent the error message when TLS is not enabled:
=> only check Certificate hostname field when TLS is enabled

Model/Api.php
- Add `rawurlencode()` to all variable $uri segments inside Api.php
=> feature/M095M01A-38 API string parameters should be url-encoded

Model/FrontControllerPlugin.php
- Add break when match found on path matching loop
=> feature/M095M01A-3 Inefficient Looping When Matching Path #411

Documentation/INSTALLATION.md
This commit updates the configuration link in the installation documentation. It currently points to the same page, but a broken anchor. This commit updates it to the configuration documentation.
=> Update configuration link

etc/vcl_snippets/recv.vcl
See https://github.com/magento/magento2/pull/30340
=> Allow to cache search results

Plugin/AdaptivePixelRationPlugin.php
- Change AdaptivePixelRationPlugin to allow for @api change on `custom_attributes` expected value type
=> [M095M01A-42] #34: [MAGENTO 2] Issue #418

Observer/ConfigurationSave.php
- Adds array index check for config data in observer
=> feature/M095M01A-45 Error when saving anything in system config #425

view/adminhtml/templates/system/config/dialogs.phtml
source of truth: https://developer.fastly.com/learning/concepts/shielding/#choosing-a-shield-location
=> Update shielding list

Documentation/Guides/Edge-Modules/EDGE-MODULE-CORS-HEADERS.md, etc/fastly_edge_modules/cors_headers.json
as per https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin#cors_and_caching
=> CORS module should return "Vary: Origin" response header

Controller/Adminhtml/FastlyCdn/Domains/PushDomains.php
=> Impossible to add domains with wildcard

Controller/GeoIP/GetAction.php, Model/Resolver/GeoIP/CountryCodeProviderInterface.php, Model/Resolver/GeoIP/HttpCountryProvider.php, etc/di.xml
=> Added country_code provider for controller fastlyCdn/geoip/getaction

etc/vcl_snippets/recv.vcl
=> check IO status more reliably

Model/Product/Image.php, Model/View/Asset/Image.php
#466 
(still testing, do not merge yet)
=> fix type check in Image

composer.json, etc/di.xml
this PR is resolve #494 
we added support only for PHP ~8.0.0
=> adding support and fix for PHP 8.0

Controller/Adminhtml/FastlyCdn/CustomSnippet/ChangeUpdateFlag.php, Controller/Adminhtml/FastlyCdn/Vcl/GetUpdateFlag.php, Controller/Adminhtml/FastlyCdn/Vcl/Upload.php
=> Fix for: GetUpdateFlag call flushes all configuration #499

Console/Command/JsonToSerialize.php, Console/Command/SerializeToJson.php, Model/Notification.php, Plugin/AdaptivePixelRatioPlugin.php, Setup/UpgradeData.php, Setup/UpgradeSchema.php
=> Fix version_compare

etc/graphql/di.xml
=> Fix for Fastly Rate Limiting - Graphql

Model/Config.php
improvement for #393  https://github.com/fastly/fastly-magento2/pull/531
=> Fix/improvement #393

Controller/Adminhtml/FastlyCdn/Vcl/Upload.php, Model/Api.php
Reverts fastly/fastly-magento2#530 due to report in #540
=> Revert "Improvements to custom VCL snippets upload logic"

Plugin/MediaStorage/App/AroundMedia.php, etc/di.xml
Prevent google bot to generate image files if deep image optimization is enabled.
=> Deep image optimization - App Media Launch prevent

Controller/Adminhtml/FastlyCdn/ImportExport/GetImportData.php, Controller/Adminhtml/FastlyCdn/ImportExport/SaveExportData.php, Controller/Adminhtml/FastlyCdn/Manifest/Save.php, Controller/Adminhtml/FastlyCdn/Manifest/ToggleModules.php, Controller/Adminhtml/FastlyCdn/Manifest/Upload.php, Controller/Adminhtml/FastlyCdn/RateLimiting/GetPaths.php, Controller/Adminhtml/FastlyCdn/RateLimiting/ToggleRateLimiting.php, Controller/Adminhtml/FastlyCdn/RateLimiting/UpdatePaths.php, Model/Config.php
=> Php 8.1 fix #551

Plugin/GraphQl/AfterRenderResult.php
=> added GrapQL header directive: stale-if-error

Setup/Patch/Data/RateLimitPath.php
Added in config placeholder for rate limits.
=> Placeholder for Rate Limits Paths

Plugin/MediaStorage/App/AroundMedia.php
=> Modification on logic - display placeholder instead of http 404 #567

Controller/GeoIP/GetAction.php
This was submitted by a customer as a fix for #549
=> Proposed fix for #549 as submitted by customer

Controller/Adminhtml/FastlyCdn/CustomSnippet/CreateCustomSnippet.php
Disallows multiple snippets using the same name, issuing a warning message to user in case a snippet with the same name already exists.
Closes #554
=> Custom snippet duplicate warning

Model/ResponsePlugin.php
=> fastly#588 - fix type check in ResponsePlugin

Model/Config.php, Plugin/MediaStorage/App/AroundMedia.php, etc/adminhtml/system.xml, etc/config.xml
this solves #591 by allowing administrators to choose if they want to serve placeholders or 404s
=> add option to serve 404s on nonexistent images

Controller/GeoIP/GetAction.php, etc/vcl_snippets/recv.vcl, view/frontend/templates/geoip/dialog.phtml, view/frontend/templates/geoip/redirect.phtml
This PR depends on #630 as it deals with varying on the `store` cookie.
=> Geo redirect loop

Console/Command/ConfigGetCommand.php, Console/Command/ConfigImportCommand.php, Console/Command/EnableCommand.php, Console/Command/GenerateVclCommand.php, Console/Command/JsonToSerialize.php, Console/Command/SerializeToJson.php, Console/Command/SuperUserCommand.php
Have been added expected return value for the CLI commands. 
Tested on Magento 2.4.6
=> cli command return success/failure added

Console/Command/EnableCommand.php, Console/Command/JsonToSerialize.php, Console/Command/SerializeToJson.php, Console/Command/SuperUserCommand.php
=> Refactored CLI commands to return CLI success or failure flags

Controller/Adminhtml/FastlyCdn/CustomSnippet/CreateCustomSnippet.php
=> Update Snippet fix

Block/GeoIp/GetAction.php
=> fix GEOIP redirection causes 404 #693
