etc/fastly.vcl
Added code to remove set-cookies from static content to match the removal of the cookie in recv.
This alleviates a session resetting issue when a new cookie is issued from static content responses from Magento
=> Fixed VCL cookie removal logic

Helper/CacheTags.php, Model/Layout/LayoutPlugin.php, Observer/InvalidateVarnishObserver.php
Created a new helper class 'CacheTags' with a method which converts long Magento Cache tags to the short ones. The method is used to modify 'X-Magento-Tags' header and for surrogate keys.
=> Short cache tags, updated purging by surrogate keys so it's compatible with new tags

Helper/CacheTags.php
We need to further shorten Magento tags. In this tweak we strip off underscores for products and catalogs and shorten cms_block and brands_brand.
=> Tweaks to Magento-Tags shortening

etc/fastly.vcl
Move up the match for static objects, and explicitly do a lookup
=> Don't pass static objects that have /checkout in their URL

Controller/Adminhtml/FastlyCdn/Vcl/Upload.php, etc/vcl_snippets/recv.vcl
Since VCL snippets are always at the top of vcl_recv we can't do an early return (pass). We have solved this by adding a request condition for /checkout however Magento stock varnish passes on catalogsearch as well so instead we'll just add req.http.x-pass which will be our indicate when to pass a request.
=> Make the pass statement more flexible

etc/config.xml
The fix for a dashboard graph:
When 'JS minification' is enabled in config (Stores>Configuration>Advanced>Developer>JavaScript Settings>Minify JavaScript Files = Yes), 
Magento2 tries to load all resources (that loaded via require.js) using .min.js suffix and URL, which is used for building graph (https://www.gstatic.com/charts/loader.js)
will be replaced by 'https://www.gstatic.com/charts/loader.min.js' and the customer gets 404.
Here is an example: https://github.com/magento/magento2/issues/5835#issuecomment-296290118
=> Prevent https://www.gstatic.com/charts/loader.js URL from minification

Model/Api.php
Bugifxes:
* Magento 2.2.x compatibility - Changes in curl wrapper caused ```CURLOPT_POSTFIELDS``` to be set twice, second time with wrong data
Other:
* Removing ```try..catch``` - curl doesn't throw one on error, and neither is any other function that was wrapped
* Using ```$headers[] = value``` instead of ```array_push()``` - it is faster and easier to read
* Using ```$client->setOptions($options);``` to set all options at once, instead of calling one by one
* Swapping ```if..elseif``` with ```switch``` due to readability of code
=> Magento22 compatibility

etc/events.xml, etc/module.xml
Add two missing events that were causing cache invalidation not to be triggered.
Example case would be saving category info with indexing mode set to 'on schedule' and 'flat tables' being turned on.
=> Add missing observers for invalidating cache upon reindex

Model/Layout/LayoutPlugin.php, Model/ResponsePlugin.php, etc/frontend/di.xml
Unlike the default Magento Varnish setup, Fastly does not use `,` as a cache tag separator, but rather spaces. This is being adjusted in one of the plugins:
https://github.com/fastly/fastly-magento2/blob/master/Model/Layout/LayoutPlugin.php#L112
However, the code above relays on premise that output will be always rendered via layout, which is not the case for ESI blocks:
https://github.com/magento/magento2/blob/2.2.0-rc2.3/app/code/Magento/PageCache/Controller/Block/Esi.php#L16-L34
As a result, any ESI block that had more than one cache tag was not invalidated properly.
Considering the above, code has been changed to utilize the plugin around the `setHeader()` to do the changes, which covers every case(if development is done following the Magento practices)
=> Refactor cache tag adjustment logic

etc/adminhtml/system.xml
Original description of the action may be misleading. It was not entirely correct for the M2.1.x and the behavior differs in Magento M2.2.x. - hence the need in improving this section
=> Change in config comment: More accurate description of the action

view/adminhtml/templates/system/config/dialogs.phtml
Base template for the modal window on Edge ACL interface was missing one column, causing the JS errors and broken interface.
=> Adjust the layout of Edge ACL admin interface

Controller/Adminhtml/FastlyCdn/Vcl/CheckAuthSetting.php, Controller/Adminhtml/FastlyCdn/Vcl/CheckTlsSetting.php, Model/Api.php
Function `_fetch` which is used to do all the API calls always logs the error. However it is sometimes called and it was expected for it to fail, so logging in all scenarios doesn't make sense.
=> Checking for Auth and Tls settings creates log entries when it shouldn't

etc/vcl_snippets/fetch.vcl, etc/vcl_snippets/recv.vcl
For discussion. This could live in the origin configuration too, but unfortunately we would need to remove the rewriting done in `recv.vcl` if we wanted to do that, so we might as well have the whole configuration of static asset caching live in Fastly.
=> Enable browser caching of signed assets

Model/PageCache/PurgeCachePlugin.php, etc/di.xml
Bugfix: When Fastly extension is turned on, Varnish purge calls are still being sent
=> Prevent PurgeCache from triggering purge on Varnish when Fastly is used

etc/vcl_snippets/recv.vcl
The response received from route 'customer/section/load' must be non cacheable for Fastly;
=> The route '/customer/section/load' added as uncacheable

etc/vcl_snippets/fetch.vcl, etc/vcl_snippets/miss.vcl, etc/vcl_snippets/pass.vcl, etc/vcl_snippets/recv.vcl
1. By default so far we were requesting all objects from origin uncompressed then
recompressing. This commit avoids compressing version static assets that are
available in /static/version and lets origin do it
2. There was a bug if a URL had /checkout/ anywhere in the URL we'd pass the URL.
Condition was added not to pass if URL is from /static/version
=> Adding few VCL optimizations

view/adminhtml/web/js/uploadvcl.js
Due to missing quote wrapping around the string in JS, admin interface for adjusting settings of _Fastly backend_ is broken.
=> Fix missing quote causing admin interface issues

etc/vcl_snippets/fetch.vcl
This appears to be a common configuration with Apache where User-Agent is set in Vary. It destroys the cache hit ratio and in most cases makes no sense hence we want to strip it out.
=> Remove User-Agent from Vary

Model/Product/Image.php
We noticed an issue with the fastly-magento2 module when Deep Image Optimization is enabled. Product images are being delivered that aren't exactly matching the requested size, causing issues with Magento 2 templates.
This code proposal changes the fastly-magento2 module request a canvas size equal to the target product image size. Aspect ratio is maintained, just like before.
Example product image URL without this change: 
`lower_manhattan_from_empire_state_building.jpg?width=88&height=110&quality=80&bg-color=255,255,255&fit=bounds `
Example product image URL with this change:
`lower_manhattan_from_empire_state_building.jpg?width=88&height=110&quality=80&bg-color=255,255,255&fit=bounds&canvas=88,110`
Adding empty pixels using formats without an alpha channel requires picking a background …
=> Add canvas parameter to product images

Block/System/Config/Form/Field/CountryMapping.php
When selecting a new GeoIP mapping for a country, only the store name is shown, as this can be the language to select the list can be filled with a lot of the same names making it hard to select the correct store. By adding the storecode to the label its easier to select the correct store.
=> Add store code to CountryMapping list to identify store

etc/vcl_snippets/recv.vcl
Rewriting version assets URLs was committed in this commit
https://github.com/fastly/fastly-magento2/commit/cb8159d9a45534a14d8b70b7da61db0c4cc8df33
Unfortunately this appears to breaks certain workflows and ultimately doesn't appear us it buys us too much. This commit undoes the rewriting.
Risk: Users who have undone the rewriting on nginx
=> Stop rewriting version assets URLs in Varnish

Model/Notification.php
When exception happens in first line of try{}, as it happened to me today, then catch{} block uses variable $url that was not defined yet.
=> Fix issue with undefined $url in catch{} when exception happens in first line of try{}

Controller/GeoIP/GetAction.php
Currently when the GeoIP redirect URL is generated, it is done in the context of the current store. This means that if the target store has a different base URL to that of the current store, the generated redirect URL is incorrect. When the user is then redirected to the URL, the switch fails as it isn't using the target store's base URL.
This can be fixed by setting the scope of the URL builder to the target store, so that it uses the base URL of the target store to build the redirect URL.
=> Fix GeoIP not working for stores with different base URL

Model/View/Asset/Image.php
This change should stop the setup:di:compile error by setting the variable type as string in the phpdoc comment _@param **string** $filePath_ and also prevent the checkout page error by removing the _**string**_ type hint from the constructor parameter
=> Removed string type hint from constructor, added phpdoc comment

etc/config.xml
Listrak appends:
- trk_contact (Definitely unique)
- trk_sid (Definitely unique)
They also append:
- trk_msg
- trk_module
This change strips them out by default
=> Ignore Listrak query parameters by default

Model/View/Asset/Image.php
* Magento is in Production mode or Magento Cloud
* Run `setup:di:compile -vvv`
* DI is successful
* DI is failing with
```
Compilation was started.
Interception cache generation... 6/7 [========================>---]  85% 3 mins 512.0 MiBErrors during compilation:
Fastly\Cdn\Model\View\Asset\Image
Incompatible argument type: Required type: string. Actual type: \Fastly\Cdn\Model\View\Asset\filePath; File: 
/Users/olehposyniak/www/testing2/vendor/fastly/magento2/Model/View/Asset/Image.php
Total Errors Count: 1
In Log.php line 92:
```
=> DI is broken due to missed argument type

etc/vcl_snippets/fetch.vcl
At Magento we are working on the feature that allows to serve images from S3 directly and cache them on Fastly side. Image optimization is also offloaded to Fastly.
Currently, Fastly image optimization works with images served by Magento backend, but does not with images served from S3 backend due to missing cache-control headers.
Proposed patch will make Fastly cache all responses from S3, even those which do not contain cache-control headers.
If you see more elegant way of solving the described issue, please share.
=> Compatibility with images served from S3 with Fastly IO

Controller/Adminhtml/FastlyCdn/RateLimiting/DisableRateLimiting.php, Model/Config.php, Model/FrontControllerPlugin.php, etc/adminhtml/system.xml, etc/di.xml
- Add ´Enable Rate Limit Logging` config flag
- Add Logger virtual type with file `/var/log/fastly-rate-limit.log`
- Add multiple log calls to describe the process of rate limiting (both path and crawler scopes)
=> M095M01A-2 [MAGENTO 2] Add logging to rate limiting

etc/adminhtml/system.xml
- Changed field type to "password" for `fastly_api_key`
=> M095M01A-3 [Magento 2] Hide API token

Console/Command/EnableCommand.php
- Added call to `cache:flush config` to the end of `fastly:config:set`, so that following commands use the update values always.
=> feature/M095M01A-12 [MAGENTO 2] Command line interface broken

view/adminhtml/web/js/backends.js, view/adminhtml/web/js/basic-authentication.js, view/adminhtml/web/js/blocking.js, view/adminhtml/web/js/custom-synthetic-pages.js, view/adminhtml/web/js/edge-acl.js, view/adminhtml/web/js/edge-dictionaries.js, view/adminhtml/web/js/image-optimization.js, view/adminhtml/web/js/maintenance.js, view/adminhtml/web/js/modly.js, view/adminhtml/web/js/rate-limiting.js, view/adminhtml/web/js/service-label.js, view/adminhtml/web/js/testconnection.js, view/adminhtml/web/js/tls.js, view/adminhtml/web/js/wafBypass.js
When I was proceeding translation for this extension, I found many JS messages where hard to translate. Using '+' operator for connecting text is easy, but this implementation way isn't better for translating these messages into other languages like Japanese. Then I replaced them into using 'replace' method and '%n' placeholder. As you know this message format is same as Magento core codes. Translators can move all placeholders into suitable place of the sentence.
=> improve message format. eliminated '+' operator for embedding variables

Model/Config.php
- As does \Magento\PageCache\Model\Config, implment use of ObjectManager to ensure instance of Json serializer on constructor of \Fastly\Cdn\Model\Config
=> feature/M095M01A-24 [JIRA] (M095M01A-24) Fatal error

Model/Api.php
If users do not want to strip any query parameters and decided to leave the UI field as blank (remove all default values), that will produce `querystring.regfilter(req.url, "^()");` which matches any query parameters and eventually strip all parameters. To remediate this, we set "&" in case if the field is blank so this doesn't match any query parameters as "&" is a delimiter of query strings.
=> Fix VCL tempalte replacement for querystring.regfilter()

etc/graphql/di.xml
This PR fixes issue #384 
All tags are shortened before cleaning cache. But currently only "frontend" pages are tagged with shortened tags.
This PR adds shortening tags for GraphQL requests which make cache cleaning consistent with previously added tags.
=> Shorten cache tags for GraphQL requests

Helper/Vcl.php
- If no active version is found, use the greater version number available as "current version"
=> feature/M095M01A-25 [Magento 2] Github issue 364

view/frontend/templates/geoip/redirect.phtml
Expected:
JS redirects user to https://example.com/stores/store/switch/?___from_store=old_store_view&___store=new_store_view
Actual:
JS redirects user to https://example.com/stores/store/switch/?___from_store=old_store_view&___store=new_store_view;, resulting in a 404
=> Fix GeoIP JS Redirect URL

Model/Config.php
there is currently unnecessarily duplicated code and we can reuse the method defined below:
https://github.com/fastly/fastly-magento2/blob/67917532e8a3f2ca330dec1f426763731afc2e92/Model/Config.php#L760-L768
=> use available method to retrieve configuration

Documentation/CONFIGURATION.md, Documentation/Guides/ACL.md, Documentation/Guides/CUSTOM-VCL-SNIPPETS.md, Documentation/Guides/Edge-Modules/EDGE-MODULE-OTHER-CMS-INTEGRATION.md, Documentation/Guides/FORCE-TLS.md, Documentation/Guides/IMAGE-OPTIMIZATION.md, Documentation/TLS.md
This commit updates some documentation links to the Fastly https://docs.fastly.com/ site as some of the pages have since moved around.
=> Update docs links to Fastly docs

view/adminhtml/web/js/historicstats.js
This PR fixes issue caused by [commit](https://github.com/magento/magento2/pull/27860/commits/4c21e460d180de2d76810cddd6a53d256113656c) where Magento/Ui/view/base/web/js/lib/knockout/bindings/datepicker.js no longer uses 'mage/calendar' dependency by default and as result we get JavaScript error and wrong behaviour when opening Fastly tab on Dashboard page.  It's caused issue in Fastly extension since it's incorrectly using dependency by using the method of the library that wasn't explicitly loaded on the page.
=> MC-38266: [Fastly] Unexpected behavior of a "Fastly" tab on the Dashboard page

etc/vcl_snippets_rate_limiting/miss.vcl, etc/vcl_snippets_rate_limiting/recv.vcl
Rate-limiting module creates a Request Settings that is turned into the below VCL code:
```c
if( req.http.Rate-Limit ) {
return(lookup);
}
```
This would break Magento site functionalities since Fastly Varnish has surprising behavior where any request method except POST is being overwritten to GET if `return(lookup)` is called for the request.
So once this rate-limiting module is enabled, request methods such as DELETE, PUT, etc no longer work as expected and the origin server receives transformed GET requests instead.
To work around this, we stash the original request method in recv and restore it in miss if rate-limit module is enabled for the request. This would cause all request methods that are not defined as cacheable in [RFC ](https://tools.ietf.org/html/rfc7231#section-4.2.3) to …
=> [Bug] honor original request method even if it's called from lookup

etc/vcl_snippets/recv.vcl
The default value for the associated configuration option explicitly handles matching "query parameters starting with"; this suggests that values not using this pattern will match the whole parameter only. The code behaves differently. This change makes the code match expectations and examples.
For example, a configuration value of `dm_i` will remove query parameters `dm_i` and `dm_id` whereas only the first is expected to be filtered. A configuration value of `utm_.*` correctly removes both `utm_one` and `utm_two`.
=> Match whole query parameter

etc/vcl_snippets_rate_limiting/recv.vcl
Continuing the previous PR: https://github.com/fastly/fastly-magento2/pull/434
Fastly Varnish would discard the request body when `return(lookup)` is called except `POST` method.
We can fake the request method to POST to save the request body then later we restore the original request method in `vcl_miss`.
current: https://fiddle.fastlydemo.net/fiddle/c9e8659c
fix: https://fiddle.fastlydemo.net/fiddle/ae94b715
\* see the `data` field of the response body
=> don't discard request body

view/adminhtml/templates/system/config/dialogs.phtml
Changed the PoP ID for Singapore from **singapore-sg** to **qpg-singapore-sg**.
=> Update shielding POP info (Singapore)

Controller/Adminhtml/FastlyCdn/Domains/PushDomains.php
https://www.icann.org/en/system/files/files/ua-factsheet-a4-17dec15-en.pdf
> • DO NOT rely on the length of a domain to determine validity. Strings can be up to 63 characters long.
the regex we use at the moment `[A-Za-z]{2,6}` is no longer valid for many new gTLDs these days. In fact, each individual label can have up to 63 octets (== 61 characters in printable string representation, [see](https://stackoverflow.com/a/32294443)).
https://tools.ietf.org/html/rfc1035#section-2.3.4
from RFC:
> To simplify implementations, the total length of a domain name (i.e.,
> label octets and label length octets) is restricted to 255 octets or
> less.
so this PR stops checking the length of TLD and checks the total length of a domain name instead for simplification.
=> stop checking TLD length and check total length

etc/vcl_snippets_basic_auth/recv.vcl
GraphQL as rest and oauth should not be covered with HTTP Auth when it is enabled. It causes all sorts of issues as Authorization headers are used for GraphQL as well.
=> Disable http auth for GraphQL endpoint

Documentation/CONFIGURATION.md, composer.json, etc/vcl_snippets/deliver.vcl, etc/vcl_snippets/fetch.vcl, etc/vcl_snippets/hash.vcl, etc/vcl_snippets/recv.vcl
[PWA-1832](https://jira.corp.magento.com/browse/PWA-1832): Treat the X-Magento-Cache-Id header as the cache key for GraphQL requests
- Blocked by [PWA-1834](https://jira.corp.magento.com/browse/PWA-1834) to have Magento serve the header
=> PWA-1832: Adding graphql caching by X-Magento-Cache-Id

etc/vcl_snippets_basic_auth/recv.vcl, etc/vcl_snippets_blocking/recv.vcl
PURGE should be safe to bypass these block rules as we require auth for PURGE anyway (ie., `Fastly-Purge-Requires-Auth`).
=> prevent PURGE requests from being blocked by custom modules

etc/vcl_snippets_basic_auth/recv.vcl
GraphQL is usually called without a slash at the end of the URL.
=> Remove slash from GraphQL exclusion

etc/vcl_snippets/hash.vcl, etc/vcl_snippets/recv.vcl
This code is in the framework code for the hash subroutine:
```
if( req.url ) {
set req.hash += req.url;
set req.hash += req.http.Host;
set req.hash += req.http.Authorization;
set req.hash += req.http.Fastly-SSL;
set req.hash += req.vcl.generation;
return (hash);
}
```
However, `req.http.Authorization` being included in the hash means that every single user will get a different request id, which is not desired; the cache should be shared between users.
To fix this, this PR takes that same block but omits the Authorization header and returns before the Fastly-side code runs.
=> Dropping Authorization from graphql hash

Observer/ConfigurationSave.php
This closes #476 
Previously on every config save, image optimization snippet was updated by Magento.
I implemented logic:
only if config option "Automatic Compression"  was changed then Magento will update snippet.
Method for updating image snippet is getting value from this config option "Automatic Compression":
https://github.com/fastly/fastly-magento2/blob/cdf380c0c551f4bf198a98f7a1264a5ccaeeebd4/Observer/ConfigurationSave.php#L121
There is no point to update this vcl snippet in other cases.
Tested on Magento 2.4.2-p2 and 2.3.6-p1.
=> fix config save - image optimization #476

Plugin/AdaptivePixelRatioPlugin.php
Fix for issue: https://github.com/fastly/fastly-magento2/issues/473
Image custom attributes are not extendable for Magento versions lower than 2.4
=> Make the image custom attributes extendable

Controller/Adminhtml/FastlyCdn/Blocking/Blocking.php, Model/Config.php, view/adminhtml/web/js/blocking.js
We're ignoring the UI selections (countries and acls) at the time of the toggle button click (Enable/Disable) and rather reading the previous state from the saved config data.
This behavior is very confusing and should be considered a bug. For example, with this scenario:
1. Enable blocking with `Allowlist` and disable it
2. Change the `Blocking Type` to `Blocklist` and enable it again
This will create an `Allowlist` VCL snippet. We should respect the UI selections rather than the previous state.
Also, another problem is that we're only updating the config when the `Update Blocking Config` button is clicked.
This PR fixes them so that we respect the UI selections as well as update the config data upon toggling.
=> Fix ambiguous behavior in Blocking toggle

Block/Cache/Additional.php, Controller/Adminhtml/FastlyCdn/Purge/ContentType.php, Controller/Adminhtml/FastlyCdn/Purge/Quick.php, Controller/Adminhtml/FastlyCdn/Purge/Store.php, Model/Config.php, Model/Layout/LayoutPlugin.php, Model/PageCache/ConfigPlugin.php, Observer/FlushAllCacheObserver.php, Observer/InvalidateVarnishObserver.php
https://github.com/fastly/fastly-magento2/pull/482
=> Fix type check

Model/Product/Image.php
latest canvas parameter requires a comma to be used, not a colon.
=> updated canvas usage

etc/fastly_edge_modules/cors_headers.json
Closes #492 
this is example from VCL file when CORS headers are enabled:
`# Snippet edgemodule_cors_headers_deliver : 45
if (req.http.Origin && !resp.http.Access-Control-Allow-Origin && !resp.http.Access-Control-Allow-Methods && !resp.http.Access-Control-Allow-Headers) {
if ( req.http.Origin ~ "^https?://google.hr" ) {
set resp.http.Access-Control-Allow-Origin = req.http.origin;
}
set resp.http.Access-Control-Allow-Methods = "GET,HEAD,POST,OPTIONS";
set resp.http.Access-Control-Allow-Headers = "Content-Type,X-company";
set resp.http.Vary:Origin = "";
}`
and configuration:
It is tested fetch from different domains and with different headers.
=> Added support for Allow Headers #492

.github/workflows/delete-bot-branch.yaml, .github/workflows/shielding-check-cron-manual.yaml, .github/workflows/shielding-check-cron.yaml
ref. https://github.com/fastly/fastly-magento2/tree/master/etc/shielding
This will run at midnight every day and open a PR if any diff is detected. And the workflow stops jobs if there's an existing PR for that to not submit duplicate PRs. Therefore, the PR title will include a hash of the target file that is used as a search keyword.
=> Add GitHub Actions to automate updating `datacenters.json`

view/adminhtml/web/js/edge-acl.js, view/adminhtml/web/js/edge-dictionaries.js, view/adminhtml/web/js/log-endpoints.js, view/adminhtml/web/js/rate-limiting.js
=> Fix javascript #544

Plugin/GraphQl/AfterRenderResult.php, etc/graphql/di.xml
=> GraphQL header directive stale-while-revalidate

Block/System/Config/Form/Field/Checkbox.php, Model/Config.php, Plugin/AdaptivePixelRatioPlugin.php, Plugin/Block/Product/View/Type/ConfigurablePlugin.php, Plugin/GalleryPlugin.php
This is fix for error:
`Deprecated Functionality: explode(): Passing null to parameter #2 ($string) of type string is deprecated in /app/dkq5e2qiq3clq_stg/vendor/fastly/magento2/Plugin/GalleryPlugin.php on line 60 in /app/dkq5e2qiq3clq_stg/vendor/magento/framework/App/ErrorHandler.php:61`
=> fix getImageOptimization PHP 8.1

Controller/Adminhtml/FastlyCdn/RateLimiting/ToggleRateLimiting.php
This fix addresses the following error ([file](https://github.com/fastly/fastly-magento2/blob/bce65d7291b273f43ee1f1faca8fa67226aa4fe6/Controller/Adminhtml/FastlyCdn/RateLimiting/ToggleRateLimiting.php#L279)):
```
strrpos(): Argument #3 ($offset) must be contained in argument #1 ($haystack) in (...)/Controller/Adminhtml/FastlyCdn/RateLimiting/ToggleRateLimiting.php:279
```
The reason for the error above is that `strrpos` cannot accept an offset parameter less than than 0 if the string is of zero-length which is is in the case that there are no rules defined.
Instead of appending to a string and then trying to remove the last occurrence of `||` like it is done now, we append to an array of rules and then join them with ` || ` as separator.
=> Rate limiting: Fix for path processing

Controller/Adminhtml/FastlyCdn/CustomSnippet/DeleteCustomSnippet.php
Current behavior:
If the custom snippet name contains an underscore (ex my_custom_vcl), then the snippet would be for instance  : **recv_100_my_custom_vcl.vcl** 
So , the snippetName return by the explode function **line 123** returns only the first part of the name (here **my**) because the explode function **line 122** split all the name parts **array("recv","100","my","custom","vcl.vcl")**.
After that, the local custom snippet is remove from the path , but the remote snippet on Fastly is never deleted because the name is wrong.
Expected behavior:
I can delete remote custom VCL even if the vcl snippet contains underscore
My fix:
I add a limit parameter (3) to the explode function on **line 122**, so that we only split in three parts (keeping the name correct even if it contains …
=> Update DeleteCustomSnippet.php (fix to accept VCL name with underscore)

Observer/InvalidateVarnishObserver.php
This issue resolves an issue of `->getIdentities()` returning invalid values (particularly, null) for some models.
=> Add check for identities type

etc/vcl_snippets/recv.vcl
We want to be able to filter out params that contain url encoded characters like ‘;' which is url-encoded to something like '%3B’.
[STRING  |  Fastly Developer Hub ](https://developer.fastly.com/reference/vcl/types/string/)
Short strings "x" decode url encoded characters, querystring.regfilter would never match anything that includes such characters.
Long strings {"x"} don’t decode url encoded characters.
Tested with Fiddle https://fiddle.fastly.dev/fiddle/1d6d6e79
=> Allow URL encoded params to be filtered out by configuration from admin

.github/workflows/code_quality.yml, Controller/Adminhtml/FastlyCdn/Blocking/AbstractBlocking.php
This PR adds testing of module installation and `setup:di:compile` to our CI testing.
It allows us to automatically test for situations where a potentially incompatible change is made to the codebase that could break in older Magento versions.
It also installs a specific version of MariaDB and ES in order to be able to install Magento 2 in the runner.
=> Test module installation in CI

Plugin/Swatches/Helper/Data/AppendSrcsetInformationPlugin.php, etc/di.xml, view/frontend/web/js/swatch-renderer-mixin.js
- initial logic for js
- implement dynamic srcset on swatches
=> Change srcset on swatch change

Controller/Adminhtml/FastlyCdn/ImportExport/GetImportData.php, Model/Api.php, Model/Importer.php
This PR changes the way edge dictionary items are imported. It sends the dictionary items in batch requests of up to 200 items at once, reducing the total time needed to import the dictionary.
=> Edge dictionary batch import

etc/vcl_snippets/deliver.vcl, etc/vcl_snippets/fetch.vcl, etc/vcl_snippets/recv.vcl
We need to vary on `store` cookie because the first request (**MISS**) could potentially contain the cookie, resulting in every subsequent request to the same URL showing as the store of the first request. This is evident when we run multiple storeviews on the same domain.
We can see the correct behavior with this PR:
1. Make a request __with__ the store cookie present:
```bash
curl -v --cookie "store=some_storeview" "https://magento-website-123.global.ssl.fastly.net/" \
| grep -A6 'switcher-language-trigger' | tail -n 3
```
output (cache **MISS**):
```html
<strong class="view-default">
<span>Some Store View</span>
</strong>
```
*Figure: request with store cookie present (we are showing the current storeview HTML)*
2. Make a request __without__ the cookie present:
```bash
curl -v …
```
=> Vary on `store` cookie

Plugin/AdaptivePixelRatioPlugin.php
When `$imageUrl` is null, `strpos` throws an error when using PHP 8.
=> Handle NULL Image URLs in Pixel Ratio Plugin

Plugin/GraphQl/AfterRenderResult.php
=> Fix for problem with removing GraphQl module

Controller/Adminhtml/FastlyCdn/Configuration/TestConnection.php, Model/Api.php
Credentials could not be tested before saving configuration. This closes #648.
=> Added flag parameter for testing credentials

Console/Command/EnableCommand.php, Controller/Adminhtml/FastlyCdn/Vcl/Upload.php, Model/Upload/Acl.php, Model/Upload/Dictionary.php
=> Fixing problems with VCL upload using CLI

view/adminhtml/web/js/init.js
=> Run init method if Fastly configuration tab is already open 

Controller/Adminhtml/FastlyCdn/Logging/CreateEndpoint.php, Controller/Adminhtml/FastlyCdn/Logging/UpdateEndpoint.php
=> Fix for real time logging (create new response condition) issue #682

Controller/Adminhtml/FastlyCdn/Logging/CreateEndpoint.php, Controller/Adminhtml/FastlyCdn/Logging/UpdateEndpoint.php, view/adminhtml/web/js/log-endpoints.js
=> Real-Time Log streaming fix #682

.github/workflows/shielding-check-cron-manual.yaml, .github/workflows/shielding-check-cron.yaml
`save-state` and `set-output` commands used in GitHub Actions are deprecated and [GitHub recommends using environment files](https://github.blog/changelog/2023-07-24-github-actions-update-on-save-state-and-set-output-commands/).
This PR updates the usage of `::set-output` to `"$GITHUB_OUTPUT"`
Instructions for envvar usage from GitHub docs:
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
=> ci: Use GITHUB_OUTPUT envvar instead of set-output command

Controller/Adminhtml/FastlyCdn/Blocking/Blocking.php
Switched to Throwable in catch statement because generic message was shown - error which doesn't extend Exception class was thrown
=> Catching Throwable in Blocking Controller

Observer/InvalidateVarnishObserver.php
Additional check which prevents default category and product cache tag purge if they are disabled - still works for specific tags
=> Additional check for tag purge

view/adminhtml/web/js/init.js
Trigger init of edge modules if tab is open by default, not only on click event
=> Edge modules tab fix

Controller/Adminhtml/FastlyCdn/Edge/Dictionary/ListAll.php, view/adminhtml/web/js/edge-dictionaries.js
Implemented check for NGWAF dictionary - shouldn't be displayed in customer listing
=> NGWAF dictionary check

Console/Command/SuperUserCommand.php, Model/Api.php
Implemented method which uses bulk update API for ACLs, use this logic for IP list update in fastly:maintenance command
=> Bulk update for ACL items in CLI
